name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  linux:
    name: ${{ matrix.os }} (${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-18.04, Ubuntu-20.04]
        compiler: [g++, clang++]

    env:
      CXX: ${{ matrix.compiler }}
      NODE_LABELS: Linux Ubuntu
      WAF_JOBS: 3

    steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: ./.jenkins

  ubuntu-ppa:
    name: Ubuntu PPA build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run build script
      run: |
        sudo apt-get -qy install software-properties-common
        sudo add-apt-repository ppa:named-data/ppa -y
        sudo apt-get -qq update
        sudo apt-get -qy install libndn-cxx-dev
        ./waf --color=yes configure --debug
        ./waf --color=yes build -j$(nproc)

  macos:
    name: Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        xcode: ['12.4', '12.5', '13.2']
        include:
        - os: macos-10.15
          xcode: '11.3'
        - os: macos-10.15
          xcode: '11.7'

    env:
      NODE_LABELS: OSX
      WAF_JOBS: 4

    steps:
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v3
    - name: Run build script
      run: ./.jenkins
